Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'Rakefile'
    - 'rakefile'
    - '**/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'decks/**/*.rb'
Metrics/LineLength:
  Max: 160
  Exclude:
    - 'db/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'decks/**/*.rb'
# Security/Eval:
#   Exclude:
#     - 'decks/**/*.rb'
Style/Documentation:
  Enabled: false
