language: ruby
sudo: false
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-9.1.6.0
matrix:
  allow_failures:
  - rvm: jruby-9.1.6.0
  - rvm: ruby-head
before_install: gem install bundler --no-document
script: bundle exec rspec spec
